api_admin_check:
    path: api/admin/login
app_logout:
    path: /logout
gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh




#index:
#    path: /
#    controller: App\Controller\DefaultController::index
